"""A SQLite cache of completed runs, keyed by what actually determines a result.

The key is a hash of three things:

1. the rendered script, exactly as it would be executed,
2. the OpenSn pack commit it was generated against,
3. the runner's configuration.

Not the spec. Two different specs that render to the same script should share a
result, and one spec whose template changed underneath it must not. Hashing the
rendered text rather than its inputs makes both of those true without anyone
maintaining a list of which spec fields matter.

The runner configuration is in the key because a replayed fixture and a
four-rank MPI run are not the same evidence, and a cache that conflated them
would let a fixture answer a question the user asked of the real solver.

The provenance header is excluded from the hash. It carries the study name and
case id, which are labels, not inputs: including them would defeat the cache
between two studies that run the same simulation.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from contextlib import closing
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator, Optional

from autoopensn.runner.base import RunResult

SCHEMA = """
CREATE TABLE IF NOT EXISTS runs (
    key          TEXT PRIMARY KEY,
    case_id      TEXT NOT NULL,
    study        TEXT,
    pack_commit  TEXT NOT NULL,
    script_sha   TEXT NOT NULL,
    runner       TEXT NOT NULL,
    runner_config TEXT NOT NULL,
    exit_code    INTEGER NOT NULL,
    wall_time    REAL NOT NULL,
    timed_out    INTEGER NOT NULL DEFAULT 0,
    replayed     INTEGER NOT NULL DEFAULT 0,
    stdout       TEXT NOT NULL,
    stderr       TEXT NOT NULL,
    directory    TEXT,
    created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS runs_by_study ON runs (study, case_id);
CREATE INDEX IF NOT EXISTS runs_by_commit ON runs (pack_commit);
"""

PROVENANCE_PREFIX = "# Generated by AutoOpenSn."


def strip_provenance(script: str) -> str:
    """The script without its generated header comment block.

    The header ends at the first blank line. Everything before it is labels.
    """
    if not script.startswith(PROVENANCE_PREFIX):
        return script
    _, separator, body = script.partition("\n\n")
    return body if separator else script


def cache_key(script: str, pack_commit: str, runner_config: dict[str, Any]) -> str:
    """Identity of a computation: what was run, against what, by what."""
    material = json.dumps(
        {
            "script": strip_provenance(script),
            "pack_commit": pack_commit,
            "runner": runner_config,
        },
        sort_keys=True,
    )
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


class RunStore:
    """Stores and retrieves completed runs.

    Not a context manager by accident: it is one, because the alternative is a
    CLI that leaves a SQLite handle open on every early exit.
    """

    def __init__(self, path: Path = Path("runs/cache.db")):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.connection = sqlite3.connect(str(self.path))
        self.connection.row_factory = sqlite3.Row
        with closing(self.connection.cursor()) as cursor:
            cursor.executescript(SCHEMA)
        self.connection.commit()

    def __enter__(self) -> "RunStore":
        return self

    def __exit__(self, *exception) -> None:
        self.close()

    def close(self) -> None:
        self.connection.close()

    # --- reading ---

    def get(self, key: str) -> Optional[RunResult]:
        row = self.connection.execute("SELECT * FROM runs WHERE key = ?", (key,)).fetchone()
        if row is None:
            return None
        return RunResult(
            case_id=row["case_id"],
            exit_code=row["exit_code"],
            stdout=row["stdout"],
            stderr=row["stderr"],
            wall_time=row["wall_time"],
            directory=Path(row["directory"]) if row["directory"] else Path("."),
            runner=row["runner"],
            command=(),
            timed_out=bool(row["timed_out"]),
            replayed=bool(row["replayed"]),
            started_at=row["created_at"],
        )

    def __contains__(self, key: str) -> bool:
        return (
            self.connection.execute(
                "SELECT 1 FROM runs WHERE key = ? LIMIT 1", (key,)
            ).fetchone()
            is not None
        )

    def entries(self, study: Optional[str] = None) -> Iterator[dict[str, Any]]:
        sql = "SELECT key, case_id, study, pack_commit, runner, exit_code, wall_time, created_at FROM runs"
        parameters: tuple = ()
        if study:
            sql += " WHERE study = ?"
            parameters = (study,)
        sql += " ORDER BY created_at DESC"
        for row in self.connection.execute(sql, parameters):
            yield dict(row)

    # --- writing ---

    def put(
        self,
        key: str,
        result: RunResult,
        *,
        script: str,
        pack_commit: str,
        runner_config: dict[str, Any],
        study: Optional[str] = None,
    ) -> None:
        """Record a completed run.

        Failed runs are cached too. A case that crashes deterministically will
        crash again, and re-running it on every invocation of a nine-point study
        wastes the user's afternoon to rediscover the same traceback. The row
        keeps its exit code, so nothing downstream mistakes it for a success.
        """
        self.connection.execute(
            """
            INSERT OR REPLACE INTO runs
                (key, case_id, study, pack_commit, script_sha, runner, runner_config,
                 exit_code, wall_time, timed_out, replayed, stdout, stderr, directory, created_at)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """,
            (
                key,
                result.case_id,
                study,
                pack_commit,
                hashlib.sha256(strip_provenance(script).encode("utf-8")).hexdigest(),
                result.runner,
                json.dumps(runner_config, sort_keys=True),
                result.exit_code,
                result.wall_time,
                int(result.timed_out),
                int(result.replayed),
                result.stdout,
                result.stderr,
                str(result.directory),
                result.started_at or datetime.now(timezone.utc).isoformat(),
            ),
        )
        self.connection.commit()

    def forget(self, key: str) -> bool:
        """Drop one cached run. Returns whether anything was removed."""
        cursor = self.connection.execute("DELETE FROM runs WHERE key = ?", (key,))
        self.connection.commit()
        return cursor.rowcount > 0

    def clear(self, study: Optional[str] = None) -> int:
        """Drop every cached run, or every run of one study."""
        if study:
            cursor = self.connection.execute("DELETE FROM runs WHERE study = ?", (study,))
        else:
            cursor = self.connection.execute("DELETE FROM runs")
        self.connection.commit()
        return cursor.rowcount
